name: Update README with Latest Commit

on:
  push:
    branches:
      - main
    
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get latest commit message
        id: get_commit_message
        run: |
          echo "::set-output name=message::$(git log -1 --pretty=format:%s)"
          
      - name: Update README.md
        run: |
          # README.md 파일에 변경 이력 섹션이 있다고 가정
          sed -i "s|.*|\n- \`\`\`${{ steps.get_commit_message.outputs.message }}\`\`\`\n|g" README.md
        
      - name: Commit changes
        run: |
          git config user.email "jihunjeong965@gmail.com"
          git config user.name "JungJihun1012"
          git add README.md
          git commit -m "Docs: Update README with latest commit" || echo "No changes to commit"
          git push