name: Update README with Latest Commit

on:
  push:
    branches:
      - main
    workflows_dispatch:
    
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get latest commit message
        id: get_commit_message
        run: |
          echo "::set-output name=message::$(git log -1 --pretty=format:%s)"
          
      - name: Update README.md
        run: |
          # README.md
          MARKER_START=""
          MARKER_END=""
          sed -i "s|.*|\n- \`\`\`${{ steps.get_commit_message.outputs.message }}\`\`\`\n|g" README.md
        
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Docs: Update README with latest commit"
          file_pattern: "README.md"